In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
data_1d = np.array([1,2,3,4,5])
data_1d

data_2d = np.array([[1,2,3],[4,5,6]])
data_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
data_1d.shape

(5,)

In [7]:
data_2d.shape

(2, 3)

In [9]:
reshape_1d = data_1d.reshape(2,3)
reshape_1d

ValueError: cannot reshape array of size 5 into shape (2,3)

In [11]:
reshape_2d = data_2d.reshape(3,2)
reshape_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
data_2d.ndim

2

Array indexing and sicing

In [19]:
print(data_1d)
print(data_2d)


print(data_1d[2])
print(data_2d[1,2])

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
3
6
